import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProviderAuth from '@/components/provider-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderAuth>{children}</ProviderAuth>
      </body>
    </html>
  )
}
