import type { Metadata } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import ProviderAuth from '@/components/provider-auth'

import './_global.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <Head>
        <title>Implement Payment</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      </Head>
      <Script type="text/javascript" src={process.env.MIDTRANS_SNAP_URL} data-client-key={process.env.MIDTRANS_CLIENT_KEY} />
      <body>
        <ProviderAuth>{children}</ProviderAuth>
      </body>
    </html>
  )
}
